# Esto configura:

#     Un servicio web llamado tareas-backend
#     Usa Docker como entorno.
#     El comando buildCommand permite construir el front
#     El comando de inicio ejecuta Apache con el comando apache2-foreground.
#     El archivo Dockerfile se encuentra dentro de la carpeta backend

services:
  - type: web
    name: tareasPHP
    env: docker
    dockerfilePath: ./tutoriales/php/tareasPHP/backend/Dockerfile
    dockerContextDir: .
    buildCommand: "npm install && npm run build"
    startCommand: docker-compose up
  
